version: "3"

services:
  proxy:
    image: nginx
    networks:
      - backend
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  redis:
    image: redis
    networks:
      - backend
    ports:
      - "6379:6379"
  ws1:
    image: websocket
    networks:
      - backend
    environment:
      - APPID=1111
  ws2:
    image: websocket
    networks:
      - backend
    environment:
      - APPID=2222
  ws3:
    image: websocket
    networks:
      - backend
    environment:
      - APPID=3333
  ws4:
    image: websocket
    networks:
      - backend
    environment:
      - APPID=4444
